/*
 * Name:        02- Even Fibonacci numbers
 * Author:      Moises Beato Nunez
 * Date:        01 Mar 2018
 * Description: Problem 2 of the PojectEuler series. Each new term in the Fibonacci sequence is generated by
 *              adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *                          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *              By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 *              find the sum of the even-valued terms.
 * Link:        https://projecteuler.net/problem=2
 */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int main()
{
    uint32_t maxvalue = 4000000; //max value is 4 Mil
    uint32_t fibo1 = 0;          //holds the previous value of the series
    uint32_t fibo2 = 1;          //holds the next value on the series
    uint32_t sum;                //hold the sum of the even numbers

    printf("Fibonacci Series blow 4 Mil(Even-Values):\n");
    while (fibo2 < maxvalue){
        fibo1 = fibo1 + fibo2;
        if (fibo1 % 2 == 0){        //check if even, then print and add
            printf("%d ", fibo1);
            sum += fibo1;
        }

        fibo2 = fibo2 + fibo1;
        if (fibo2 % 2 == 0){        //check if even, then print and add
            sum += fibo2;
            printf("%d ", fibo2);
        }
    }
    printf("\nSum of the Series: %d \n",sum);
    return 0;
}
